### ISSUE TITLE
Schemas and Tables are "case sensitive"

### ISSUE THREAD

**Issue by sebasmonia** [sebasmonia/pyquebec#10]
The query for the tables and columns, at least in MS SQL Server, returns elements just as they were created.
Pypyodbc returns the column names in lowercase.

Maybe we should make everything lowercase?

Pro: Consistency
Con: readability.

**Comment by ferantivero** [comment]
exactly as they were fetched from the DB, IMO

**Comment by jmaltube** [comment]
1$ 7#1$ $0 #4RD 70 R34D???

If not, why would lower case would be any worse?

lowercase ftw

**Comment by jdecarli** [comment]
As fetched from the DB. We don't know if the system consuming the DB requires the "casing"

**Comment by sebasmonia** [comment]
@ferantivero even if ita inconsistent with the names in the results?

@jdecarli I think the standard demands case insensitiveness

**Comment by sebasmonia** [comment]
2 votes to 1 to keep them as is.

Closing bug.
