### ISSUE TITLE
Include query in HTML Formatter

### ISSUE THREAD

**Issue by sebasmonia** [sebasmonia/pyquebec#17]
In the proto-versions of pyquebec, the HTML page included the text of the query executed.
It was a nice feature.

This was possible because the module returned a "ResultSet" object instead of a plain list, and this had the query and some other info about the results, on top of the formatters call.

``` python
# how it used to work
result = db.exec_sql("SELECT * FROM Table")
result.to_html()
result.query  # would return the SQL
```

Is it worth it to add the ResultSet again just for this feature? other things we could add by using this object?

**Comment by ferantivero** [comment]
I would say no. Reasons behind:
#1 this is just for the direct statement exec. The qb provides you with the preview thing
#2 I would prefer something like list the last executed statements and results from DB:

db.log //container with the last execs
db.log[42].preview() // here the query qb-like
db.log[42].result.to_html() //prev results 
db.log[42].go() // be able to re-exe qb-like

**Comment by sebasmonia** [comment]
#1: We could add more stuff in the future. I just don't see what right now, so I have a hard time seeing the value.

#2: The DataBase has a statement_history with all the SQL executed in that instance in a list. Not the QBs since you can also use plain SQL.

You can always keep a ref to the query object yourself...but now that you mention it, QBs are quite small, keeping references to them in the DataBase that spun them shouldn't be too expensive.

In the sample code, you have the results as part of the query object (if I got it right).
That one is more dangerous in terms of memory and also we would need to add a mechanism to invalidate (or just delete) the results after you change the query...or risk confusion for the user.

---

Wirtten on vriutal kebyaord. May cantoin typos.

**Comment by sebasmonia** [comment]
Will close this issue, discard the results object, and add another one for "queries history".
