### ISSUE TITLE
[from UT] it is possible to create an invalid QueryBuilder instance

### ISSUE THREAD

**Issue by ferantivero** [sebasmonia/pyquebec#5]
more info: just execute test_querybuilderctor_nonedbinstance_then_raises_ValueError and :boom:

**Comment by sebasmonia** [comment]
Since there's no point in making the ctor "private", I will make that a required parameter.

**Comment by ferantivero** [comment]
sounds good

**Comment by sebasmonia** [comment]
Fixed in commit 3b718ec626be20f92feaf6ab269702dbdf72f20c
